### ISSUE TITLE
Problèmes de gestion du .gitignore et du poids du dépôt

### ISSUE THREAD

**Issue by Leuchak** [yvanross/LOG430-STM#18]
Clone le repos prend plus d'une minutes sur une bonne connection internet. On se retrouve limité par l'api de Githug. Actuellement, le repos fait plus de 500MiB. Plusieurs fichiers inutiles ont été inclus dans Git, ce qui augmente la charge du projet de manière non nécéssaires.

Pour résoudre ce problème, je propose les actions suivantes:
1. Réviser et optimiser le fichier .gitignore. Assurez vous que les fichiers que vous souhaitez conservé ne soit pas inclus dans un fichier .gitignore. Exemple microservices/UI/.vscode/{extensions,launch,tasks}.json. Si c'est le cas, veuillez les exclures ou les enlever puis effectué un commit.
2. Exécuter les commandes `git rm --cached -rf .` et `git add .`;  La première stage tous les fichiers pour suppression et la seconde stage tous les fichiers pour l'ajout à l'exception de ceux présent dans des fichier .gitignore. Le résultat de la commande va préparer un commit pour supprimer tous les fichiers présent dans git mais qui devrait être supprimer. Par exemple, tous les fichiers dans les dossiers .vs ne devrait pas être inclus dans Git.
3. Effectuer un commit pour consolider ces modifications et nettoyer le dépôt de tous les fichiers inutiles. Vous pouvez vous assurers que seuls les fichiers inutiles vont être inclus dans le commit.

Ces actions devraient contribuer à alléger le poids du projet et à améliorer sa gestion.
Idéalement, cet action devrait être effectué sur la branche principale, mais en raison de la persistance des fichiers inutiles sur chaque branches, ces manipulations doivent être répliquées sur toutes les branches du projet.

**Comment by DavidDaniel18** [comment]
![image](https://github.com/yvanross/LOG430-STM/assets/38500310/8111014c-e082-4550-be52-3d9ff6e08cba)

La branche principale fait 130mb décompressé et 38 mb en zip. 
Merci pour les conseils

**Comment by Leuchak** [comment]
do a git clone, it's 500 mb et ça prizs 2minutes pour clone
![image](https://github.com/yvanross/LOG430-STM/assets/21264237/1ac33c9b-291f-4464-b346-aa216cde6e77)

**Comment by Leuchak** [comment]
le dossier lui meme est légé, mais chaque commit est cumulatif sur la taille. Toutes modification ajouter dans l'historique git va resté dans l'historique. Ajouter un fichier et supprimer un fichier va conserver le fichier dans l'historique. Cloné le repos va donc prendre de plus en plus de temps.

Plusieurs fichiers du .gitignore se font track quand meme et donc git les inclus alors qu'ils ne devrait pas l'être. Tous les fichiers auto généré comme ceux dans les dossiers .vs ou les dossiers obj

**Comment by Leuchak** [comment]
Si on prend tout le code, le repos pourait être aussi légé que 30mb. Présentement dans la branche la plus a jour, le code au total fait seulement 4.8M
